Release v0.1
codex-team/pycapella pull request #1
Opened 2017-12-08 20:27 UTC by n0str

2017-12-10 12:44 UTC, neSpecc requested changes

2017-12-10 12:44 UTC, neSpecc commented on README.rst
> +Python SDK for capella.pics
не мерджите без нормального ридми плз

2017-12-11 21:33 UTC, gohabereg commented on pycapella/api.py
> +                    url += '/{}/{}x{}'.format(filter, *params)
resize и crop перепутаны. И может все таки elseif в последнем случае ставить?

2017-12-13 19:40 UTC, neSpecc commented on pycapella/api.py
> +                    url += '/{}/{}x{}'.format(filter, *params)
да, elseif будет понятнее, сейчас не ясно какой фильтр применяется. А еще лучше switch

2017-12-13 20:07 UTC, neSpecc approved these changes

2017-12-13 21:46 UTC, merged